name: Announce the release of new version on Slack
on:
  push:
    branches: [notifications]
jobs:
  slack:
    runs-on: ubuntu-latest
    steps:
      - uses: andreasgylche/SharyUI@notifications
        with:
          webhook_url: https://hooks.slack.com/services/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
          title: 🚀 v1.0.0
          body: This major release means that we are live!
          context: Slack release BOT
