name: Announce the release of new version on Slack
on:
  push:
    branches: [notifications]
jobs:
  slack:
    runs-on: ubuntu-latest
    steps:
      - uses: andreasgylche/SharyUI@notifications
        with:
          webhook_url: https://hooks.slack.com/services/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
          title: 🚀 v1.0.0
          body: This major release means that we are live!
          context: Slack release BOT

name:  Announce the release of new version on Slack
author: Roshan Pratap Katel
description: Slack Release BOT used by Roshan 
inputs:
  webhook_url:
    required: true
    description: Slack webhook URL
  title:
    required: true
    description: Message title
runs:
  using: 'composite'
  steps:
    - name: Announce on Slack 📢
      shell: bash
      run: |
        header='{
          "type": "header",
          "text": {
          "type": "plain_text",
          "text": "${{ inputs.title }}"
          }
        },'
        divider='{
          "type": "divider"
        },'
        # Slack markdown doesn't accept empty `text`
        if [ ! -z '${{ inputs.body }}' ]
        then
          body='{
            "type": "section",
            "text": {
            "type": "mrkdwn",
            "text": "${{ inputs.body }}"
            }
          },'
        fi
        context='{
          "type": "context",
          "elements": [
          {
            "type": "plain_text",
            "text": "${{ inputs.context }}"
          }
          ]
        }'
        blocks='"blocks": [
          '$header'
          '$divider'
          '$body'
          '$context'
        ]'
        data='{'$blocks'}'
        
        curl https://hooks.slack.com/services/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 \
          --request POST \
          --header 'Content-type: application/json' \
          --data "$data"
