name: Announce the release of new version on Slack
run-name: ${{ github.actor }} has published new release for the library 🚀
on:
  push:
    branches: [notifications, main]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "🐧 This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "🔎 The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: Check out repository code
        uses: actions/checkout@v3
      - run: echo "💡 The ${{ github.repository }} repository has been cloned to the runner."
      - run: echo "🖥️ The workflow is now ready to test your code on the runner."
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      - run: echo "🍏 This job's status is ${{ job.status }}."
  slack:
    needs: Explore-GitHub-Actions
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: New updates released
        run: |
          echo "::set-output name=TITLE::$(git show -1 --format='%s' -s)"
        id: latest_commit
      - name: Announce on Slack
        run: |
          curl https://hooks.slack.com/services/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 \
            --request POST \
            --header 'Content-type: application/json' \
            --data \
              '{
                "blocks": [
                  "type": "header",
                  "text": {
                    "type": "plain text"
                  }
                ]
              }'
